### ISSUE TITLE
[feature-request] JavaScript port.

### ISSUE THREAD

**Issue by trusktr** [micahpearlman/MonkVG#45]
It'd be nice to have something like this for WebGL.

**Comment by trusktr** [comment]
This is too awesome, but I really want it in WebGL. Maybe I'll try porting it at some point...

**Comment by micahpearlman** [comment]
That would be cool. I don't know a thing about WebGL but let me know if I can advise on the code base.

**Comment by trusktr** [comment]
WebGL is very similar to OpenGL ES (well, it is written as a JavaScript interface for OpenGL ES). So many of the calls are very similar. For example, `glTextImage2d()` would be `gl.textImage2d()` in JavaScript, calling a method on the `gl` context object.

In almost every case, whenever I see `gl.someMethod` in JavaScript, I just look up `glSomeMethod` to find OpenGL documentation on it. It is literally almost a one-to-one mapping, so porting to JavaScript wouldn't be difficult, just time consuming to rewrite.

f.e. `glEnable(GL_DEPTH_TEST)` becomes `gl.enable(gl.DEPTH_TEST)`. Almost everything maps one-to-one.

**Comment by trusktr** [comment]
A big difference is that everything is easier in WebGL. For example, you can pass a reference to a `<img />` HTML element into the `gl.textImage2d` instead of a data array, and the webgl engine does the magic taking the data from the image element behind the scenes. It has lot's of such shortcuts that make the webgl coding experience easier.
